### ISSUE TITLE
App label issues when following dotted path convention

### ISSUE THREAD

**Issue by jaycle** [lekjos/django-custom-admin-pages#36]
**Describe the bug**
Django recommends that for local apps, you specify the `INSTALLED_APPS` via the dotted path to the `AppConfig` (see [INSTALLED_APPS](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-INSTALLED_APPS)).

In order to pass the check added by [1.2.2](https://github.com/lekjos/django-custom-admin-pages/pull/29/files#diff-e395226c39a6835b139a03996bec5c820cbfe45bd3d4d8451dd9df7b6879b721R112-R114), the app_label needs to be the same string used `INSTALLED_APPS`. However, if this is used, then we can no longer match on app_label `CustomAdminSite`'s `get_app_list()`.

**To Reproduce**
1. Have an app named "my_app" with AppConfig at `my_app.apps.MyAppConfig`.
2. Add the dotted path to INSTALLED_APPS
3. Create a View extendeing AdminBaseView, and use "my_app" as the app_label.

**Expected behavior**
Correct app is identified.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 14.1.1 
 - Browser Firefox (irrelevant)

**Smartphone (please complete the following information):**

**Additional context**
I believe we would expect `found` to be set to True in this scenario ([ref](https://github.com/lekjos/django-custom-admin-pages/blob/0db999e69f3e1d5a7797e0ba46b62749a92f7c08/django_custom_admin_pages/admin.py#L209C25-L209C26))
```py
for app in app_list:
    if view_app_label == app.get("app_label", "").lower():
        found = True
 ```
 
But since it falls through, another issue occurs on line 210 because `get_installed_apps()` returns a flat list of strings, whereas `app_list` is a list of dicts containing 'name', 'app_label', etc.
 
 This causes the following TypeError:
 ```
  File "<path>/.venv/lib/python3.11/site-packages/django_custom_admin_pages/admin.py", line 210, in get_app_list
    remaining_apps = set(set(get_installed_apps())).difference(app_list)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by jaycle** [comment]
In the additional context, I believe there may be some other issue when an app isn't found (comparing incorrect types). But I believe everything works when the startup check from [here](https://github.com/lekjos/django-custom-admin-pages/pull/29/files#diff-e395226c39a6835b139a03996bec5c820cbfe45bd3d4d8451dd9df7b6879b721R112-R114) is simply removed. At least this is true in my testing.

**Comment by lekjos** [comment]
@jaycle  thanks for the report! I'll patch it this weekend

**Comment by lekjos** [comment]
@jaycle (Also, I really appreciate the detail you provided. It will make this much quicker to address)

**Comment by jaycle** [comment]
I know you added tests, so you have confidence this works. But just wanted to follow up to say the update is working for my project, too, as of [1.2.4](https://github.com/lekjos/django-custom-admin-pages/releases/tag/1.2.4). Thanks so much for the quick response and fix!
